import os
import uuid
from typing import Any

import defusedxml.minidom as minidom
from jinja2 import Environment, FileSystemLoader, select_autoescape

from apps.execution.database.context import current_session
from apps.execution.database.models import TranslationJob

# Setup Jinja2 environment
TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")
env = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    autoescape=select_autoescape(default_for_string=True, default=True),
)


def extract_appearance(item: dict[str, Any]) -> str | None:
    """Extract grid layout metadata properties into standard Enketo appearance classes.

    Parses USDM item layout properties (`cols`, `column_span`, `span`) directly or from
    a nested layout/grid object, converting width factors into OpenRosa/Enketo classes (`w1`-`w4`).

    Args:
        item (dict[str, Any]): The USDM study item definition dictionary.

    Returns:
        str | None: The computed appearance class, or None if no layout is specified.
    """
    # Check item.cols, item.column_span, item.span
    keys = ["cols", "column_span", "span"]
    for k in keys:
        if k in item:
            val = item[k]
            if str(val) in ["1", "2", "3", "4"]:
                return f"w{val}"

    # Check layout sub-objects
    for sub in ["layout", "grid"]:
        if sub in item and isinstance(item[sub], dict):
            for k in keys:
                if k in item[sub]:
                    val = item[sub][k]
                    if str(val) in ["1", "2", "3", "4"]:
                        return f"w{val}"
    return None


async def process_translation(
    study_id: str, payload: dict[str, Any], session_factory: Any
) -> None:
    """Background worker that translates USDM payload into CDISC ODM and OpenRosa XML layouts.

    Args:
        study_id (str): The unique identifier of the source study.
        payload (dict[str, Any]): The raw USDM protocol payload.
        session_factory (Any): The SQLAlchemy asynchronous session factory.

    Returns:
        None
    """
    async with session_factory() as session:
        async with session.begin():
            # Setup the DB session in context so our audit logger can find it
            token = current_session.set(session)

            job = TranslationJob(study_id=study_id, status="PROCESSING")
            session.add(job)
            await session.flush()

            try:
                # Requirement 6: Validate input structures against schema translation rules
                if not payload or not isinstance(payload, dict):
                    raise ValueError("Payload must be a dictionary.")
                if "protocol" not in payload:
                    raise ValueError(
                        "Validation Failed: 'protocol' missing from study definition."
                    )

                # Process items for templates
                raw_items = payload.get("protocol", {}).get("items", [])
                processed_items = []
                for item in raw_items:
                    item_id = item.get("id")
                    if not item_id:
                        item_id = f"item_{uuid.uuid4().hex[:8]}"

                    item_name = item.get("name", "Unknown Field")
                    item_type = item.get("type", "string")
                    appearance = extract_appearance(item)

                    processed_items.append(
                        {
                            "id": item_id,
                            "name": item_name,
                            "type": item_type,
                            "appearance": appearance,
                        }
                    )

                template_data = {
                    "study_id": study_id,
                    "name": payload.get("name", f"Study {study_id}"),
                    "items": processed_items,
                }

                # Render templates
                odm_template = env.get_template("odm_template.xml.j2")
                odm_xml_str = odm_template.render(**template_data)

                openrosa_template = env.get_template("openrosa_template.xml.j2")
                openrosa_xml_str = openrosa_template.render(**template_data)

                # Format outputs via minidom to guarantee compatibility with existing expectations
                # We strip out whitespace-only text nodes created by jinja templating before formatting
                def pretty_print(xml_string: str) -> str:
                    """
                    Format an XML string with indentation for better readability.

                    Removes whitespace-only text nodes generated by Jinja2 templates before
                    applying standard formatting via minidom to ensure expected line breaks.

                    Args:
                        xml_string (str): The raw XML string to format.

                    Returns:
                        str: The pretty-printed XML string.
                    """
                    dom = minidom.parseString(xml_string)
                    # Remove blank text nodes so toprettyxml doesn't add extra newlines
                    for node in dom.getElementsByTagName("*"):
                        for child in list(node.childNodes):
                            # 3 is the integer value for Node.TEXT_NODE
                            if child.nodeType == 3 and not child.data.strip():
                                node.removeChild(child)
                    return dom.toprettyxml(indent="  ")

                odm_str = pretty_print(odm_xml_str)
                openrosa_str = pretty_print(openrosa_xml_str)

                job.odm_payload = odm_str
                job.openrosa_payload = openrosa_str
                job.status = "COMPLETED"

            except Exception as e:
                # Constraint: fail gracefully
                job.status = "FAILED"
                job.error_message = str(e)
            finally:
                # Update job execution status
                await session.flush()
                current_session.reset(token)
