import datetime
from typing import Awaitable, Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

from apps.execution.database.context import current_session
from packages.security.context import (
    current_change_reason,
    current_ip_address,
    current_timestamp,
    current_user_id,
)


class ContextResetMiddleware(BaseHTTPMiddleware):
    """
    Middleware to ensure database context variables are properly reset per request.

    This prevents context variable leakage across asynchronous task executions
    by cleanly applying, then removing, request-bound tokens upon completion.
    """

    async def dispatch(
        self, request: Request, call_next: Callable[[Request], Awaitable[Response]]
    ) -> Response:
        """
        Intercepts HTTP requests to initialize and safely tear down database contexts.

        Args:
            request (Request): The incoming HTTP request.
            call_next (Callable[[Request], Awaitable[Response]]): The next middleware or route handler.

        Returns:
            Response: The HTTP response generated by the application.
        """
        user_id = request.headers.get("x-user-id", "system")
        change_reason = request.headers.get("x-change-reason", "system_operation")

        # Extract IP Address
        ip_address = request.headers.get(
            "x-forwarded-for", request.client.host if request.client else "127.0.0.1"
        )
        if "," in ip_address:
            ip_address = ip_address.split(",")[0].strip()

        user_token = current_user_id.set(user_id)
        reason_token = current_change_reason.set(change_reason)
        ip_token = current_ip_address.set(ip_address)
        ts_token = current_timestamp.set(
            datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
        )

        # Reset the database session token if any
        session_token = current_session.set(None)

        try:
            response = await call_next(request)
            return response
        finally:
            current_user_id.reset(user_token)
            current_change_reason.reset(reason_token)
            current_ip_address.reset(ip_token)
            current_timestamp.reset(ts_token)
            current_session.reset(session_token)
