import os
import re
import sys
import subprocess

ADR_DIR = "docs/adr"
INDEX_FILE = os.path.join(ADR_DIR, "index.md")
IGNORE_FILES = {"TEMPLATE.md", "index.md"}

# Regex patterns
FILENAME_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}-.+\.md$")
DATE_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}")
TITLE_PATTERN_OLD = re.compile(r"^# .*\d{4}-\d{2}-\d{2}.*$")
TITLE_PATTERN_NEW = re.compile(r"^# ADR-(?:\d+|\[NUMBER\]): .*$")

REQUIRED_SECTIONS_OLD = [
    "## Status",
    "## Context",
    "## Decision",
    "## Alternatives Considered",
    "## Trade-offs",
]

REQUIRED_SECTIONS_NEW = [
    "## 1. Context & Problem Statement",
    "## 2. Decision Drivers & Constraints",
    "## 3. Options Considered",
    "## 4. Decision Outcome",
    "## 5. Consequences & Trade-offs",
    "## 6. Implementation & Verification",
]


def run_git_command(args: list[str]) -> tuple[str, str]:
    """Helper to run a system git command safely."""
    try:
        res = subprocess.run(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True,
            timeout=10,
        )
        return res.stdout.strip(), res.stderr.strip()
    except Exception as e:
        return "", str(e)


def is_architectural_file(filepath: str) -> bool:
    """
    Checks if a file path is considered an architectural change according to:
    - Dependencies configuration (pyproject.toml, package.json)
    - API Gateway modifications (apps/gateway/)
    - Core data models (packages/core-models/)
    - Database/storage model changes/migrations (apps/execution/database/, 'migrations', 'models')

    Ignores tests, docs, scripts, github workflows, markdown/txt files, etc.
    """
    # Exclude directories we don't treat as architectural logic
    if (
        filepath.startswith("tests/")
        or filepath.startswith("docs/")
        or filepath.startswith("scripts/")
        or filepath.startswith(".github/")
        or filepath.endswith(".md")
        or filepath.endswith(".txt")
        or filepath.endswith(".gitignore")
    ):
        return False

    # 1. Dependencies configuration
    if filepath in ("pyproject.toml", "package.json"):
        return True

    # 2. API Gateway and router modifications
    if filepath.startswith("apps/gateway/"):
        return True

    # 3. Core data models
    if filepath.startswith("packages/core-models/"):
        return True

    # 4. Storage model changes or migrations under execution
    if filepath.startswith("apps/execution/database/") or "migrations" in filepath or "models" in filepath:
        if filepath.startswith("apps/execution/"):
            return True

    return False


def get_changed_files() -> set[str]:
    """Retrieves list of changed files from CI environment or local Git."""
    changed_files = set()

    # 1. Read from changed_files.txt (if generated by CI / previous step)
    if os.path.exists("changed_files.txt"):
        try:
            with open("changed_files.txt", "r") as f:
                for line in f:
                    if line.strip():
                        changed_files.add(line.strip())
        except Exception:
            pass

    # 2. Try git diff HEAD^ (standard on PR branch checks)
    if not changed_files:
        stdout, _ = run_git_command(["git", "diff", "--name-only", "HEAD^"])
        if stdout:
            changed_files.update(stdout.splitlines())

    # 3. Try git diff against origin/main
    if not changed_files:
        stdout, _ = run_git_command(["git", "diff", "--name-only", "origin/main"])
        if stdout:
            changed_files.update(stdout.splitlines())

    # 4. Try git diff against HEAD~1
    if not changed_files:
        stdout, _ = run_git_command(["git", "diff", "--name-only", "HEAD~1"])
        if stdout:
            changed_files.update(stdout.splitlines())

    # 5. Always include unstaged/staged local changes
    stdout, _ = run_git_command(["git", "status", "--porcelain"])
    if stdout:
        for line in stdout.splitlines():
            if len(line) > 3:
                # Format: "M  path/to/file" or "?? path/to/file"
                filepath = line[3:].strip()
                changed_files.add(filepath)

    return changed_files


def check_architectural_changes_require_adr(changed_files: set[str]) -> bool:
    """
    Checks if there are architectural changes, and if so, verifies that
    a corresponding new ADR is added inside docs/adr/.
    """
    architectural_changes = [f for f in changed_files if is_architectural_file(f)]
    if not architectural_changes:
        return True

    # Check if a new ADR file is present in changed_files
    new_adr_added = False
    for f in changed_files:
        if f.startswith("docs/adr/") and FILENAME_PATTERN.match(os.path.basename(f)):
            # Ensure it is not deleted
            if os.path.exists(f):
                new_adr_added = True
                break

    if not new_adr_added:
        print("Error: Architectural changes detected, but no corresponding ADR found in docs/adr/.")
        print("Architectural files changed:")
        for f in architectural_changes:
            print(f"  - {f}")
        print("Please add a new ADR markdown file under docs/adr/ following the template.")
        return False

    return True


def validate_existing_adrs() -> bool:
    """Validates structure, filenames, and index alignment of existing ADRs."""
    if not os.path.isdir(ADR_DIR):
        print(f"Error: Directory {ADR_DIR} not found.")
        return False

    try:
        with open(INDEX_FILE, "r") as f:
            index_content = f.read()
    except Exception as e:
        print(f"Error reading {INDEX_FILE}: {e}")
        return False

    all_passed = True

    # Check for ADRs outside the proper folder
    for root, _, files in os.walk("."):
        if ".git" in root or ".venv" in root or "node_modules" in root:
            continue
        for filename in files:
            if not filename.endswith(".md"):
                continue
            if FILENAME_PATTERN.match(filename):
                # Ensure it resides in docs/adr
                expected_dir = os.path.join(".", "docs", "adr")
                if os.path.abspath(root) != os.path.abspath(expected_dir):
                    print(
                        f"Error: ADR file '{filename}' found outside the proper directory ({root}). Must reside in {ADR_DIR}."
                    )
                    all_passed = False

    for filename in os.listdir(ADR_DIR):
        if not filename.endswith(".md"):
            continue
        if filename in IGNORE_FILES:
            continue

        filepath = os.path.join(ADR_DIR, filename)

        # 1. Check filename pattern
        if not FILENAME_PATTERN.match(filename):
            print(
                f"Error: File '{filename}' does not follow the standard chronological date pattern (YYYY-MM-DD-...)."
            )
            all_passed = False

        # 2. Check if file is in index
        if f"({filename})" not in index_content:
            print(
                f"Error: File '{filename}' is missing from the index log ({INDEX_FILE})."
            )
            all_passed = False

        # 3. Read file and check contents
        try:
            with open(filepath, "r") as f:
                content = f.read()
        except Exception as e:
            print(f"Error reading {filepath}: {e}")
            all_passed = False
            continue

        lines = content.split("\n")

        # Check title
        is_new_format = False
        if lines and TITLE_PATTERN_NEW.match(lines[0]):
            is_new_format = True
        elif not lines or not TITLE_PATTERN_OLD.match(lines[0]):
            print(
                f"Error: File '{filename}' title (first line) does not contain the correct format (old or new)."
            )
            all_passed = False

        # Check required sections
        missing_sections = []
        required_sections = (
            REQUIRED_SECTIONS_NEW if is_new_format else REQUIRED_SECTIONS_OLD
        )
        for section in required_sections:
            if section not in content:
                missing_sections.append(section)

        if missing_sections:
            print(
                f"Error: File '{filename}' is missing required sections: {', '.join(missing_sections)}"
            )
            all_passed = False

    return all_passed


def main():
    existing_valid = validate_existing_adrs()

    changed_files = get_changed_files()
    arch_valid = check_architectural_changes_require_adr(changed_files)

    if not existing_valid or not arch_valid:
        print("ADR validation failed.")
        sys.exit(1)

    print("All ADRs passed validation.")


if __name__ == "__main__":
    main()
